### ISSUE TITLE
2 save buttons on one page? 

### ISSUE THREAD

**Issue by brookr** [6529-Collections/6529seize-frontend#120]
I don't love it... if it can't be just one form, it should be tabbed, or have a sidebar nav. 

<img width="820" alt="Screenshot 2023-10-23 at 12 04 39 AM" src="https://github.com/6529-Collections/6529seize-frontend/assets/11095/0b0c59c1-759d-430f-840e-8bc34435f4d8">

**Comment by brookr** [comment]
Can we do a "Profile" and a "PFP" tab or something? Just scrolling down for more fields in a different form doesn't seem like the right UX. 

Is this something for the next iteration? Other thoughts?

**Comment by analyticsflowee** [comment]
yes this is something we plan to do next iteration, i think Profile and PFP tabs is what we are going. We did it more distinct view, i think you should refresh your cache
![Screenshot 2023-10-30 at 12 46 34](https://github.com/6529-Collections/6529seize-frontend/assets/49652774/059faf67-aa19-4d94-8079-b91b0bbda26d)

**Comment by brookr** [comment]
This has been resolved.
